### ISSUE TITLE
Need Mcode to modify steps per unit

### ISSUE THREAD

**Issue by danthompson41** [Voxel8/Marlin#91]
We want to be able to modify steps per unit, based on micron / mm. Carmen should know the details of what we want to see from it

**Comment by sean-v8** [comment]
@danthompson41, does `M92` already take care of this?

**Comment by danthompson41** [comment]
I actually saw that, and figured it might. We may want to modify it / duplicate it to take in Micron / MM, as that's what our measuring equipment spits out. I believe it does cover the same ground though

**Comment by lewisgroup** [comment]
This should be lower priority. I brought it up yesterday because I thought
it would fix an immediate problem Carmen had, but it turns out it will not.
That being said this could still be useful and should be implemented if
there is time to spare.

On Tue, Mar 15, 2016 at 12:37 PM, Daniel Thompson <notifications@github.com>
wrote:

> I actually saw that, and figured it might. We may want to modify it /
> duplicate it to take in Micron / MM, as that's what our measuring equipment
> spits out. I believe it does cover the same ground though
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Voxel8/Marlin/issues/91#issuecomment-196912345
>



-- 
Jack Minardi
jack.minardi.org
jack@minardi.org

**Comment by danthompson41** [comment]
M272!
